- name: Preparing the exercise3
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Create SSH config file with StrictHostKeyChecking no
      ansible.builtin.copy:
        dest: '/home/{{ user }}/.ssh/config'
        content: |
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0600'

    - name: Get user SSH key
      ansible.builtin.slurp:
        src: "/home/{{ user }}/.ssh/id_rsa.pub"
      register: usersshkey

    - name: Create the idrsa secret
      kubernetes.core.k8s:
        state: present
        template: "exercise3-secret.yaml.j2"
      register: secretidrsa
      until: secretidrsa is succeeded
      retries: 60
      delay: 10
      failed_when: secretidrsa is failed or secretidrsa.failed

    - name: Creating exercise3 virtual machine
      kubernetes.core.k8s:
        state: present
        template: "exercise3-vm.yaml.j2"
      register: exercise3vm
      until: exercise3vm is succeeded
      retries: 60
      delay: 10
      failed_when: exercise3vm is failed or exercise3vm.failed

    - name: Creating exercise3 service
      kubernetes.core.k8s:
        state: present
        template: "exercise3-service.yaml.j2"
      register: exercise3svc
      until: exercise3svc is succeeded
      retries: 60
      delay: 10
      failed_when: exercise3svc is failed or exercise3svc.failed

    - name: Creating exercise3 route
      kubernetes.core.k8s:
        state: present
        template: "exercise3-break-route.yaml.j2"
      register: exercise3route
      until: exercise3route is succeeded
      retries: 60
      delay: 10
      failed_when: exercise3route is failed or exercise3route.failed

    - name: Creating curl image pod for tests
      kubernetes.core.k8s:
        state: present
        template: "curl-pod.yaml.j2"
      register: exercise3curlpod
      until: exercise3curlpod is succeeded
      retries: 60
      delay: 10
      failed_when: exercise3curlpod is failed or exercise3curlpod.failed

    - name: Wait for exercise3
      ansible.builtin.command:
        cmd: virtctl ssh -i /home/{{ user }}/.ssh/id_rsa  lab-user@exercise3
      ignore_errors: true
      no_log: false
      register: testssh
      until:
        - testssh.rc == 0
      retries: 20
      delay: 10

