- name: Cleaning the exercise1
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Clean the exercise1
      kubernetes.core.k8s:
        state: absent
        template: "exercise1-break-vm.yaml.j2"
      register: cleanvm
      until: cleanvm is succeeded
      retries: 60
      delay: 10
      failed_when: cleanvm is failed or cleanvm.failed

    - name: Wait for the Virtual Machine to be removed
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        namespace: "namespace-{{ user }}"
        name: "exercises"
      register: cleanvm
      retries: 60
      delay: 2
      until: cleanvm.resources | length == 0
