- name: Cleaning the exercise5
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:

    - name: Removing data disk 1 from virtual machine
      ansible.builtin.command: virtctl removevolume exercise5 --volume-name=exercise5-vol-data1 --persist
      register: exercise5datadisk1
      ignore_errors: true

    - name: Delete virtual machine
      kubernetes.core.k8s:
        state: absent
        template: "exercise5-create-vm.yaml.j2"
      register: breakvm
      until: breakvm is succeeded
      retries: 60
      delay: 10
      failed_when: breakvm is failed or breakvm.failed

    - name: Removing data volume from virtual machine
      kubernetes.core.k8s:
        state: absent
        template: "exercise5-fixdatavol.yaml.j2"
      register: exercise5datavol
      until: exercise5datavol is succeeded
      retries: 5
      delay: 10
      failed_when: exercise5datavol is failed or exercise5datavol.failed

    - name: Wait for the Virtual Machine to be removed
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        namespace: "namespace-{{ user }}"
        name: "exercise5"
      register: cleanvm
      retries: 60
      delay: 2
      until: cleanvm.resources | length == 0

    # - name: Get user SSH key
    #   ansible.builtin.slurp:
    #     src: "/home/{{ user }}/.ssh/id_rsa.pub"
    #   register: usersshkey

    # - name: Removing the idrsa secret
    #   kubernetes.core.k8s:
    #     state: absent
    #     template: "exercise5-secret.yaml.j2"
    #   register: secretidrsa
    #   until: secretidrsa is succeeded
    #   retries: 60
    #   delay: 10
    #   failed_when: secretidrsa is failed or secretidrsa.failed
